// <auto-generated />
using System;
using BiteAI.Services.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BiteAI.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251108134710_AddUserProfiles")]
    partial class AddUserProfiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AllergyTypeEntityUserProfile", b =>
                {
                    b.Property<int>("AllergiesValue")
                        .HasColumnType("integer");

                    b.Property<string>("UserProfilesId")
                        .HasColumnType("text");

                    b.HasKey("AllergiesValue", "UserProfilesId");

                    b.HasIndex("UserProfilesId");

                    b.ToTable("UserProfileAllergies", (string)null);
                });

            modelBuilder.Entity("BiteAI.Services.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<int?>("ActivityLevelTypeEntityValue")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("GenderTypeEntityValue")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityLevelTypeEntityValue");

                    b.HasIndex("GenderTypeEntityValue");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BiteAI.Services.Data.Entities.Enums.ActivityLevelTypeEntity", b =>
                {
                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Value");

                    b.ToTable("ActivityLevels");

                    b.HasData(
                        new
                        {
                            Value = 0,
                            Name = "NotSpecified"
                        },
                        new
                        {
                            Value = 1,
                            Name = "Sedentary"
                        },
                        new
                        {
                            Value = 2,
                            Name = "LightlyActive"
                        },
                        new
                        {
                            Value = 3,
                            Name = "ModeratelyActive"
                        },
                        new
                        {
                            Value = 4,
                            Name = "VeryActive"
                        },
                        new
                        {
                            Value = 5,
                            Name = "ExtraActive"
                        });
                });

            modelBuilder.Entity("BiteAI.Services.Data.Entities.Enums.AllergyTypeEntity", b =>
                {
                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Value");

                    b.ToTable("AllergyTypes");

                    b.HasData(
                        new
                        {
                            Value = 0,
                            Name = "None"
                        },
                        new
                        {
                            Value = 1,
                            Name = "Peanuts"
                        },
                        new
                        {
                            Value = 2,
                            Name = "TreeNuts"
                        },
                        new
                        {
                            Value = 3,
                            Name = "Dairy"
                        },
                        new
                        {
                            Value = 4,
                            Name = "Eggs"
                        },
                        new
                        {
                            Value = 5,
                            Name = "Soy"
                        },
                        new
                        {
                            Value = 6,
                            Name = "Wheat"
                        },
                        new
                        {
                            Value = 7,
                            Name = "Gluten"
                        },
                        new
                        {
                            Value = 8,
                            Name = "Fish"
                        },
                        new
                        {
                            Value = 9,
                            Name = "Shellfish"
                        },
                        new
                        {
                            Value = 10,
                            Name = "Sesame"
                        },
                        new
                        {
                            Value = 11,
                            Name = "Mustard"
                        },
                        new
                        {
                            Value = 12,
                            Name = "Celery"
                        },
                        new
                        {
                            Value = 13,
                            Name = "Sulphites"
                        },
                        new
                        {
                            Value = 14,
                            Name = "Lupin"
                        },
                        new
                        {
                            Value = 15,
                            Name = "Molluscs"
                        },
                        new
                        {
                            Value = 16,
                            Name = "Crustaceans"
                        },
                        new
                        {
                            Value = 17,
                            Name = "Milk"
                        },
                        new
                        {
                            Value = 18,
                            Name = "Cheese"
                        },
                        new
                        {
                            Value = 19,
                            Name = "Yogurt"
                        },
                        new
                        {
                            Value = 20,
                            Name = "Butter"
                        },
                        new
                        {
                            Value = 21,
                            Name = "Almonds"
                        },
                        new
                        {
                            Value = 22,
                            Name = "Walnuts"
                        },
                        new
                        {
                            Value = 23,
                            Name = "Cashews"
                        },
                        new
                        {
                            Value = 24,
                            Name = "Pistachios"
                        },
                        new
                        {
                            Value = 25,
                            Name = "Hazelnuts"
                        },
                        new
                        {
                            Value = 26,
                            Name = "BrazilNuts"
                        },
                        new
                        {
                            Value = 27,
                            Name = "MacadamiaNuts"
                        },
                        new
                        {
                            Value = 28,
                            Name = "Pecans"
                        },
                        new
                        {
                            Value = 29,
                            Name = "PineNuts"
                        },
                        new
                        {
                            Value = 30,
                            Name = "Coconut"
                        },
                        new
                        {
                            Value = 31,
                            Name = "Kiwi"
                        },
                        new
                        {
                            Value = 32,
                            Name = "Banana"
                        },
                        new
                        {
                            Value = 33,
                            Name = "Avocado"
                        },
                        new
                        {
                            Value = 34,
                            Name = "Pineapple"
                        },
                        new
                        {
                            Value = 35,
                            Name = "Mango"
                        },
                        new
                        {
                            Value = 36,
                            Name = "Papaya"
                        },
                        new
                        {
                            Value = 37,
                            Name = "PassionFruit"
                        },
                        new
                        {
                            Value = 38,
                            Name = "Guava"
                        },
                        new
                        {
                            Value = 39,
                            Name = "DragonFruit"
                        },
                        new
                        {
                            Value = 40,
                            Name = "Durian"
                        },
                        new
                        {
                            Value = 41,
                            Name = "Jackfruit"
                        },
                        new
                        {
                            Value = 42,
                            Name = "Rambutan"
                        },
                        new
                        {
                            Value = 43,
                            Name = "Lychee"
                        },
                        new
                        {
                            Value = 44,
                            Name = "Longan"
                        },
                        new
                        {
                            Value = 45,
                            Name = "Mangosteen"
                        },
                        new
                        {
                            Value = 46,
                            Name = "Salak"
                        },
                        new
                        {
                            Value = 47,
                            Name = "SnakeFruit"
                        },
                        new
                        {
                            Value = 48,
                            Name = "CustardApple"
                        },
                        new
                        {
                            Value = 49,
                            Name = "Soursop"
                        },
                        new
                        {
                            Value = 50,
                            Name = "Atemoya"
                        });
                });

            modelBuilder.Entity("BiteAI.Services.Data.Entities.Enums.DietTypeEntity", b =>
                {
                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Value");

                    b.ToTable("DietTypes");

                    b.HasData(
                        new
                        {
                            Value = 0,
                            Name = "Standard"
                        },
                        new
                        {
                            Value = 1,
                            Name = "Vegetarian"
                        },
                        new
                        {
                            Value = 2,
                            Name = "Vegan"
                        },
                        new
                        {
                            Value = 3,
                            Name = "Keto"
                        },
                        new
                        {
                            Value = 4,
                            Name = "LowCarb"
                        },
                        new
                        {
                            Value = 5,
                            Name = "Paleo"
                        },
                        new
                        {
                            Value = 6,
                            Name = "Mediterranean"
                        },
                        new
                        {
                            Value = 7,
                            Name = "GlutenFree"
                        },
                        new
                        {
                            Value = 8,
                            Name = "DairyFree"
                        });
                });

            modelBuilder.Entity("BiteAI.Services.Data.Entities.Enums.FoodDislikeTypeEntity", b =>
                {
                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Value");

                    b.ToTable("FoodDislikeTypes");

                    b.HasData(
                        new
                        {
                            Value = 0,
                            Name = "None"
                        },
                        new
                        {
                            Value = 1,
                            Name = "Broccoli"
                        },
                        new
                        {
                            Value = 2,
                            Name = "BrusselsSprouts"
                        },
                        new
                        {
                            Value = 3,
                            Name = "Cauliflower"
                        },
                        new
                        {
                            Value = 4,
                            Name = "Cabbage"
                        },
                        new
                        {
                            Value = 5,
                            Name = "Kale"
                        },
                        new
                        {
                            Value = 6,
                            Name = "Spinach"
                        },
                        new
                        {
                            Value = 7,
                            Name = "Asparagus"
                        },
                        new
                        {
                            Value = 8,
                            Name = "Artichokes"
                        },
                        new
                        {
                            Value = 9,
                            Name = "Beets"
                        },
                        new
                        {
                            Value = 10,
                            Name = "Radishes"
                        },
                        new
                        {
                            Value = 11,
                            Name = "Turnips"
                        },
                        new
                        {
                            Value = 12,
                            Name = "Parsnips"
                        },
                        new
                        {
                            Value = 13,
                            Name = "Rutabagas"
                        },
                        new
                        {
                            Value = 14,
                            Name = "Celery"
                        },
                        new
                        {
                            Value = 15,
                            Name = "Fennel"
                        },
                        new
                        {
                            Value = 16,
                            Name = "Leeks"
                        },
                        new
                        {
                            Value = 17,
                            Name = "Onions"
                        },
                        new
                        {
                            Value = 18,
                            Name = "Garlic"
                        },
                        new
                        {
                            Value = 19,
                            Name = "Shallots"
                        },
                        new
                        {
                            Value = 20,
                            Name = "Scallions"
                        },
                        new
                        {
                            Value = 21,
                            Name = "Chives"
                        },
                        new
                        {
                            Value = 22,
                            Name = "Mushrooms"
                        },
                        new
                        {
                            Value = 23,
                            Name = "Eggplant"
                        },
                        new
                        {
                            Value = 24,
                            Name = "Zucchini"
                        },
                        new
                        {
                            Value = 25,
                            Name = "Squash"
                        },
                        new
                        {
                            Value = 26,
                            Name = "Cucumber"
                        },
                        new
                        {
                            Value = 27,
                            Name = "BellPeppers"
                        },
                        new
                        {
                            Value = 28,
                            Name = "ChiliPeppers"
                        },
                        new
                        {
                            Value = 29,
                            Name = "Jalapenos"
                        },
                        new
                        {
                            Value = 30,
                            Name = "Okra"
                        },
                        new
                        {
                            Value = 31,
                            Name = "GreenBeans"
                        },
                        new
                        {
                            Value = 32,
                            Name = "Peas"
                        },
                        new
                        {
                            Value = 33,
                            Name = "LimaBeans"
                        },
                        new
                        {
                            Value = 34,
                            Name = "KidneyBeans"
                        },
                        new
                        {
                            Value = 35,
                            Name = "BlackBeans"
                        },
                        new
                        {
                            Value = 36,
                            Name = "PintoBeans"
                        },
                        new
                        {
                            Value = 37,
                            Name = "Chickpeas"
                        },
                        new
                        {
                            Value = 38,
                            Name = "Lentils"
                        },
                        new
                        {
                            Value = 39,
                            Name = "Tofu"
                        },
                        new
                        {
                            Value = 40,
                            Name = "Tempeh"
                        },
                        new
                        {
                            Value = 41,
                            Name = "Seitan"
                        },
                        new
                        {
                            Value = 42,
                            Name = "Quinoa"
                        },
                        new
                        {
                            Value = 43,
                            Name = "Couscous"
                        },
                        new
                        {
                            Value = 44,
                            Name = "Bulgur"
                        },
                        new
                        {
                            Value = 45,
                            Name = "Farro"
                        },
                        new
                        {
                            Value = 46,
                            Name = "Barley"
                        },
                        new
                        {
                            Value = 47,
                            Name = "Rye"
                        },
                        new
                        {
                            Value = 48,
                            Name = "Oats"
                        },
                        new
                        {
                            Value = 49,
                            Name = "Millet"
                        },
                        new
                        {
                            Value = 50,
                            Name = "Amaranth"
                        },
                        new
                        {
                            Value = 51,
                            Name = "Buckwheat"
                        },
                        new
                        {
                            Value = 52,
                            Name = "Sorghum"
                        },
                        new
                        {
                            Value = 53,
                            Name = "Teff"
                        },
                        new
                        {
                            Value = 54,
                            Name = "Spelt"
                        },
                        new
                        {
                            Value = 55,
                            Name = "Kamut"
                        },
                        new
                        {
                            Value = 56,
                            Name = "Einkorn"
                        },
                        new
                        {
                            Value = 57,
                            Name = "Emmer"
                        },
                        new
                        {
                            Value = 58,
                            Name = "Freekeh"
                        },
                        new
                        {
                            Value = 59,
                            Name = "WildRice"
                        },
                        new
                        {
                            Value = 60,
                            Name = "BrownRice"
                        },
                        new
                        {
                            Value = 61,
                            Name = "WhiteRice"
                        },
                        new
                        {
                            Value = 62,
                            Name = "BasmatiRice"
                        },
                        new
                        {
                            Value = 63,
                            Name = "JasmineRice"
                        },
                        new
                        {
                            Value = 64,
                            Name = "ArborioRice"
                        },
                        new
                        {
                            Value = 65,
                            Name = "SushiRice"
                        },
                        new
                        {
                            Value = 66,
                            Name = "BlackRice"
                        },
                        new
                        {
                            Value = 67,
                            Name = "RedRice"
                        },
                        new
                        {
                            Value = 68,
                            Name = "GlutinousRice"
                        },
                        new
                        {
                            Value = 69,
                            Name = "ParboiledRice"
                        },
                        new
                        {
                            Value = 70,
                            Name = "ConvertedRice"
                        },
                        new
                        {
                            Value = 71,
                            Name = "Beef"
                        },
                        new
                        {
                            Value = 72,
                            Name = "Pork"
                        },
                        new
                        {
                            Value = 73,
                            Name = "Chicken"
                        },
                        new
                        {
                            Value = 74,
                            Name = "Turkey"
                        },
                        new
                        {
                            Value = 75,
                            Name = "Duck"
                        },
                        new
                        {
                            Value = 76,
                            Name = "Goose"
                        },
                        new
                        {
                            Value = 77,
                            Name = "Lamb"
                        },
                        new
                        {
                            Value = 78,
                            Name = "Veal"
                        },
                        new
                        {
                            Value = 79,
                            Name = "Rabbit"
                        },
                        new
                        {
                            Value = 80,
                            Name = "Venison"
                        },
                        new
                        {
                            Value = 81,
                            Name = "Bison"
                        },
                        new
                        {
                            Value = 82,
                            Name = "Elk"
                        },
                        new
                        {
                            Value = 83,
                            Name = "Ostrich"
                        },
                        new
                        {
                            Value = 84,
                            Name = "Emu"
                        },
                        new
                        {
                            Value = 85,
                            Name = "Quail"
                        },
                        new
                        {
                            Value = 86,
                            Name = "Pheasant"
                        },
                        new
                        {
                            Value = 87,
                            Name = "CornishHen"
                        },
                        new
                        {
                            Value = 88,
                            Name = "Squab"
                        },
                        new
                        {
                            Value = 89,
                            Name = "Salmon"
                        },
                        new
                        {
                            Value = 90,
                            Name = "Tuna"
                        },
                        new
                        {
                            Value = 91,
                            Name = "Cod"
                        },
                        new
                        {
                            Value = 92,
                            Name = "Halibut"
                        },
                        new
                        {
                            Value = 93,
                            Name = "Swordfish"
                        },
                        new
                        {
                            Value = 94,
                            Name = "MahiMahi"
                        },
                        new
                        {
                            Value = 95,
                            Name = "Grouper"
                        },
                        new
                        {
                            Value = 96,
                            Name = "Snapper"
                        },
                        new
                        {
                            Value = 97,
                            Name = "Flounder"
                        },
                        new
                        {
                            Value = 98,
                            Name = "Sole"
                        },
                        new
                        {
                            Value = 99,
                            Name = "Trout"
                        },
                        new
                        {
                            Value = 100,
                            Name = "Catfish"
                        },
                        new
                        {
                            Value = 101,
                            Name = "Tilapia"
                        },
                        new
                        {
                            Value = 102,
                            Name = "Shrimp"
                        },
                        new
                        {
                            Value = 103,
                            Name = "Crab"
                        },
                        new
                        {
                            Value = 104,
                            Name = "Lobster"
                        },
                        new
                        {
                            Value = 105,
                            Name = "Clams"
                        },
                        new
                        {
                            Value = 106,
                            Name = "Mussels"
                        },
                        new
                        {
                            Value = 107,
                            Name = "Oysters"
                        },
                        new
                        {
                            Value = 108,
                            Name = "Scallops"
                        },
                        new
                        {
                            Value = 109,
                            Name = "Squid"
                        },
                        new
                        {
                            Value = 110,
                            Name = "Octopus"
                        },
                        new
                        {
                            Value = 111,
                            Name = "Calamari"
                        },
                        new
                        {
                            Value = 112,
                            Name = "SeaUrchin"
                        },
                        new
                        {
                            Value = 113,
                            Name = "Roe"
                        },
                        new
                        {
                            Value = 114,
                            Name = "Caviar"
                        },
                        new
                        {
                            Value = 115,
                            Name = "Anchovies"
                        },
                        new
                        {
                            Value = 116,
                            Name = "Sardines"
                        },
                        new
                        {
                            Value = 117,
                            Name = "Herring"
                        },
                        new
                        {
                            Value = 118,
                            Name = "Mackerel"
                        },
                        new
                        {
                            Value = 119,
                            Name = "Bluefish"
                        },
                        new
                        {
                            Value = 120,
                            Name = "Monkfish"
                        },
                        new
                        {
                            Value = 121,
                            Name = "Skate"
                        },
                        new
                        {
                            Value = 122,
                            Name = "Eel"
                        },
                        new
                        {
                            Value = 123,
                            Name = "Conch"
                        },
                        new
                        {
                            Value = 124,
                            Name = "Abalone"
                        },
                        new
                        {
                            Value = 125,
                            Name = "Milk"
                        },
                        new
                        {
                            Value = 126,
                            Name = "Cheese"
                        },
                        new
                        {
                            Value = 127,
                            Name = "Yogurt"
                        },
                        new
                        {
                            Value = 128,
                            Name = "Butter"
                        },
                        new
                        {
                            Value = 129,
                            Name = "Cream"
                        },
                        new
                        {
                            Value = 130,
                            Name = "IceCream"
                        },
                        new
                        {
                            Value = 131,
                            Name = "CottageCheese"
                        },
                        new
                        {
                            Value = 132,
                            Name = "Ricotta"
                        },
                        new
                        {
                            Value = 133,
                            Name = "Mozzarella"
                        },
                        new
                        {
                            Value = 134,
                            Name = "Cheddar"
                        },
                        new
                        {
                            Value = 135,
                            Name = "Parmesan"
                        },
                        new
                        {
                            Value = 136,
                            Name = "Gouda"
                        },
                        new
                        {
                            Value = 137,
                            Name = "Brie"
                        },
                        new
                        {
                            Value = 138,
                            Name = "Camembert"
                        },
                        new
                        {
                            Value = 139,
                            Name = "Roquefort"
                        },
                        new
                        {
                            Value = 140,
                            Name = "Feta"
                        },
                        new
                        {
                            Value = 141,
                            Name = "GoatCheese"
                        },
                        new
                        {
                            Value = 142,
                            Name = "BlueCheese"
                        },
                        new
                        {
                            Value = 143,
                            Name = "Swiss"
                        },
                        new
                        {
                            Value = 144,
                            Name = "Provolone"
                        },
                        new
                        {
                            Value = 145,
                            Name = "MontereyJack"
                        },
                        new
                        {
                            Value = 146,
                            Name = "Colby"
                        },
                        new
                        {
                            Value = 147,
                            Name = "American"
                        },
                        new
                        {
                            Value = 148,
                            Name = "Velveeta"
                        },
                        new
                        {
                            Value = 149,
                            Name = "Eggs"
                        },
                        new
                        {
                            Value = 150,
                            Name = "Mayonnaise"
                        },
                        new
                        {
                            Value = 151,
                            Name = "Aioli"
                        },
                        new
                        {
                            Value = 152,
                            Name = "TartarSauce"
                        },
                        new
                        {
                            Value = 153,
                            Name = "Hollandaise"
                        },
                        new
                        {
                            Value = 154,
                            Name = "Bearnaise"
                        },
                        new
                        {
                            Value = 155,
                            Name = "CaesarDressing"
                        },
                        new
                        {
                            Value = 156,
                            Name = "RanchDressing"
                        },
                        new
                        {
                            Value = 157,
                            Name = "ThousandIsland"
                        },
                        new
                        {
                            Value = 158,
                            Name = "ItalianDressing"
                        },
                        new
                        {
                            Value = 159,
                            Name = "FrenchDressing"
                        },
                        new
                        {
                            Value = 160,
                            Name = "BalsamicVinaigrette"
                        },
                        new
                        {
                            Value = 161,
                            Name = "OilAndVinegar"
                        },
                        new
                        {
                            Value = 162,
                            Name = "HoneyMustard"
                        },
                        new
                        {
                            Value = 163,
                            Name = "BlueCheeseDressing"
                        },
                        new
                        {
                            Value = 164,
                            Name = "RussianDressing"
                        },
                        new
                        {
                            Value = 165,
                            Name = "SesameGinger"
                        },
                        new
                        {
                            Value = 166,
                            Name = "Teriyaki"
                        },
                        new
                        {
                            Value = 167,
                            Name = "SoySauce"
                        },
                        new
                        {
                            Value = 168,
                            Name = "Worcestershire"
                        },
                        new
                        {
                            Value = 169,
                            Name = "HotSauce"
                        },
                        new
                        {
                            Value = 170,
                            Name = "Sriracha"
                        },
                        new
                        {
                            Value = 171,
                            Name = "Tabasco"
                        },
                        new
                        {
                            Value = 172,
                            Name = "BuffaloSauce"
                        },
                        new
                        {
                            Value = 173,
                            Name = "BBQ"
                        },
                        new
                        {
                            Value = 174,
                            Name = "Ketchup"
                        },
                        new
                        {
                            Value = 175,
                            Name = "Mustard"
                        },
                        new
                        {
                            Value = 176,
                            Name = "Relish"
                        },
                        new
                        {
                            Value = 177,
                            Name = "Pickles"
                        },
                        new
                        {
                            Value = 178,
                            Name = "Olives"
                        },
                        new
                        {
                            Value = 179,
                            Name = "Capers"
                        },
                        new
                        {
                            Value = 180,
                            Name = "Horseradish"
                        },
                        new
                        {
                            Value = 181,
                            Name = "Wasabi"
                        },
                        new
                        {
                            Value = 182,
                            Name = "Apples"
                        },
                        new
                        {
                            Value = 183,
                            Name = "Bananas"
                        },
                        new
                        {
                            Value = 184,
                            Name = "Oranges"
                        },
                        new
                        {
                            Value = 185,
                            Name = "Grapes"
                        },
                        new
                        {
                            Value = 186,
                            Name = "Strawberries"
                        },
                        new
                        {
                            Value = 187,
                            Name = "Blueberries"
                        },
                        new
                        {
                            Value = 188,
                            Name = "Raspberries"
                        },
                        new
                        {
                            Value = 189,
                            Name = "Blackberries"
                        },
                        new
                        {
                            Value = 190,
                            Name = "Cranberries"
                        },
                        new
                        {
                            Value = 191,
                            Name = "Pineapple"
                        },
                        new
                        {
                            Value = 192,
                            Name = "Mango"
                        },
                        new
                        {
                            Value = 193,
                            Name = "Papaya"
                        },
                        new
                        {
                            Value = 194,
                            Name = "Kiwi"
                        },
                        new
                        {
                            Value = 195,
                            Name = "PassionFruit"
                        },
                        new
                        {
                            Value = 196,
                            Name = "Guava"
                        },
                        new
                        {
                            Value = 197,
                            Name = "DragonFruit"
                        },
                        new
                        {
                            Value = 198,
                            Name = "Durian"
                        },
                        new
                        {
                            Value = 199,
                            Name = "Jackfruit"
                        },
                        new
                        {
                            Value = 200,
                            Name = "Rambutan"
                        },
                        new
                        {
                            Value = 201,
                            Name = "Lychee"
                        },
                        new
                        {
                            Value = 202,
                            Name = "Longan"
                        },
                        new
                        {
                            Value = 203,
                            Name = "Mangosteen"
                        },
                        new
                        {
                            Value = 204,
                            Name = "Salak"
                        },
                        new
                        {
                            Value = 205,
                            Name = "SnakeFruit"
                        },
                        new
                        {
                            Value = 206,
                            Name = "CustardApple"
                        },
                        new
                        {
                            Value = 207,
                            Name = "Soursop"
                        },
                        new
                        {
                            Value = 208,
                            Name = "Atemoya"
                        },
                        new
                        {
                            Value = 209,
                            Name = "Cherries"
                        },
                        new
                        {
                            Value = 210,
                            Name = "Peaches"
                        },
                        new
                        {
                            Value = 211,
                            Name = "Plums"
                        },
                        new
                        {
                            Value = 212,
                            Name = "Apricots"
                        },
                        new
                        {
                            Value = 213,
                            Name = "Nectarines"
                        },
                        new
                        {
                            Value = 214,
                            Name = "Pears"
                        },
                        new
                        {
                            Value = 215,
                            Name = "Lemons"
                        },
                        new
                        {
                            Value = 216,
                            Name = "Limes"
                        },
                        new
                        {
                            Value = 217,
                            Name = "Grapefruit"
                        },
                        new
                        {
                            Value = 218,
                            Name = "Tangerines"
                        },
                        new
                        {
                            Value = 219,
                            Name = "Clementines"
                        },
                        new
                        {
                            Value = 220,
                            Name = "Mandarins"
                        },
                        new
                        {
                            Value = 221,
                            Name = "Pomelo"
                        },
                        new
                        {
                            Value = 222,
                            Name = "Kumquats"
                        },
                        new
                        {
                            Value = 223,
                            Name = "Calamansi"
                        },
                        new
                        {
                            Value = 224,
                            Name = "Yuzu"
                        },
                        new
                        {
                            Value = 225,
                            Name = "BuddhaHand"
                        },
                        new
                        {
                            Value = 226,
                            Name = "FingerLimes"
                        },
                        new
                        {
                            Value = 227,
                            Name = "Chocolate"
                        },
                        new
                        {
                            Value = 228,
                            Name = "DarkChocolate"
                        },
                        new
                        {
                            Value = 229,
                            Name = "MilkChocolate"
                        },
                        new
                        {
                            Value = 230,
                            Name = "WhiteChocolate"
                        },
                        new
                        {
                            Value = 231,
                            Name = "Cocoa"
                        },
                        new
                        {
                            Value = 232,
                            Name = "Carob"
                        },
                        new
                        {
                            Value = 233,
                            Name = "Licorice"
                        },
                        new
                        {
                            Value = 234,
                            Name = "Peppermint"
                        },
                        new
                        {
                            Value = 235,
                            Name = "Spearmint"
                        },
                        new
                        {
                            Value = 236,
                            Name = "Cinnamon"
                        },
                        new
                        {
                            Value = 237,
                            Name = "Nutmeg"
                        },
                        new
                        {
                            Value = 238,
                            Name = "Cloves"
                        },
                        new
                        {
                            Value = 239,
                            Name = "Allspice"
                        },
                        new
                        {
                            Value = 240,
                            Name = "Cardamom"
                        },
                        new
                        {
                            Value = 241,
                            Name = "Coriander"
                        },
                        new
                        {
                            Value = 242,
                            Name = "Cumin"
                        },
                        new
                        {
                            Value = 243,
                            Name = "FennelSeeds"
                        },
                        new
                        {
                            Value = 244,
                            Name = "Fenugreek"
                        },
                        new
                        {
                            Value = 245,
                            Name = "MustardSeeds"
                        },
                        new
                        {
                            Value = 246,
                            Name = "PoppySeeds"
                        },
                        new
                        {
                            Value = 247,
                            Name = "SesameSeeds"
                        },
                        new
                        {
                            Value = 248,
                            Name = "SunflowerSeeds"
                        },
                        new
                        {
                            Value = 249,
                            Name = "PumpkinSeeds"
                        },
                        new
                        {
                            Value = 250,
                            Name = "ChiaSeeds"
                        },
                        new
                        {
                            Value = 251,
                            Name = "Flaxseeds"
                        },
                        new
                        {
                            Value = 252,
                            Name = "HempSeeds"
                        },
                        new
                        {
                            Value = 253,
                            Name = "PineNuts"
                        },
                        new
                        {
                            Value = 254,
                            Name = "Almonds"
                        },
                        new
                        {
                            Value = 255,
                            Name = "Walnuts"
                        },
                        new
                        {
                            Value = 256,
                            Name = "Cashews"
                        },
                        new
                        {
                            Value = 257,
                            Name = "Pistachios"
                        },
                        new
                        {
                            Value = 258,
                            Name = "Hazelnuts"
                        },
                        new
                        {
                            Value = 259,
                            Name = "BrazilNuts"
                        },
                        new
                        {
                            Value = 260,
                            Name = "MacadamiaNuts"
                        },
                        new
                        {
                            Value = 261,
                            Name = "Pecans"
                        },
                        new
                        {
                            Value = 262,
                            Name = "Chestnuts"
                        },
                        new
                        {
                            Value = 263,
                            Name = "Coconut"
                        },
                        new
                        {
                            Value = 264,
                            Name = "Peanuts"
                        },
                        new
                        {
                            Value = 265,
                            Name = "Salt"
                        },
                        new
                        {
                            Value = 266,
                            Name = "Pepper"
                        },
                        new
                        {
                            Value = 267,
                            Name = "Paprika"
                        },
                        new
                        {
                            Value = 268,
                            Name = "ChiliPowder"
                        },
                        new
                        {
                            Value = 269,
                            Name = "CurryPowder"
                        },
                        new
                        {
                            Value = 270,
                            Name = "GaramMasala"
                        },
                        new
                        {
                            Value = 271,
                            Name = "TacoSeasoning"
                        },
                        new
                        {
                            Value = 272,
                            Name = "ItalianSeasoning"
                        },
                        new
                        {
                            Value = 273,
                            Name = "HerbsDeProvence"
                        },
                        new
                        {
                            Value = 274,
                            Name = "PoultrySeasoning"
                        },
                        new
                        {
                            Value = 275,
                            Name = "PumpkinPieSpice"
                        },
                        new
                        {
                            Value = 276,
                            Name = "ApplePieSpice"
                        },
                        new
                        {
                            Value = 277,
                            Name = "ChineseFiveSpice"
                        },
                        new
                        {
                            Value = 278,
                            Name = "CajunSeasoning"
                        },
                        new
                        {
                            Value = 279,
                            Name = "CreoleSeasoning"
                        },
                        new
                        {
                            Value = 280,
                            Name = "OldBay"
                        },
                        new
                        {
                            Value = 281,
                            Name = "LemonPepper"
                        },
                        new
                        {
                            Value = 282,
                            Name = "GarlicPowder"
                        },
                        new
                        {
                            Value = 283,
                            Name = "OnionPowder"
                        },
                        new
                        {
                            Value = 284,
                            Name = "Thyme"
                        },
                        new
                        {
                            Value = 285,
                            Name = "Rosemary"
                        },
                        new
                        {
                            Value = 286,
                            Name = "Sage"
                        },
                        new
                        {
                            Value = 287,
                            Name = "Oregano"
                        },
                        new
                        {
                            Value = 288,
                            Name = "Basil"
                        },
                        new
                        {
                            Value = 289,
                            Name = "Parsley"
                        },
                        new
                        {
                            Value = 290,
                            Name = "Cilantro"
                        },
                        new
                        {
                            Value = 291,
                            Name = "Dill"
                        },
                        new
                        {
                            Value = 292,
                            Name = "Tarragon"
                        },
                        new
                        {
                            Value = 293,
                            Name = "Chervil"
                        },
                        new
                        {
                            Value = 294,
                            Name = "Sorrel"
                        },
                        new
                        {
                            Value = 295,
                            Name = "Borage"
                        },
                        new
                        {
                            Value = 296,
                            Name = "Lovage"
                        },
                        new
                        {
                            Value = 297,
                            Name = "SummerSavory"
                        },
                        new
                        {
                            Value = 298,
                            Name = "WinterSavory"
                        },
                        new
                        {
                            Value = 299,
                            Name = "Marjoram"
                        },
                        new
                        {
                            Value = 300,
                            Name = "Hyssop"
                        });
                });

            modelBuilder.Entity("BiteAI.Services.Data.Entities.Enums.GenderTypeEntity", b =>
                {
                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Value");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Value = 1,
                            Name = "Male"
                        },
                        new
                        {
                            Value = 2,
                            Name = "Female"
                        });
                });

            modelBuilder.Entity("BiteAI.Services.Data.Entities.Enums.MealTypeEntity", b =>
                {
                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Value");

                    b.ToTable("MealTypes");

                    b.HasData(
                        new
                        {
                            Value = 0,
                            Name = "Breakfast"
                        },
                        new
                        {
                            Value = 1,
                            Name = "Lunch"
                        },
                        new
                        {
                            Value = 2,
                            Name = "Dinner"
                        },
                        new
                        {
                            Value = 3,
                            Name = "Snack"
                        });
                });

            modelBuilder.Entity("BiteAI.Services.Data.Entities.GroceryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Checked")
                        .HasColumnType("boolean");

                    b.Property<Guid>("GroceryListId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroceryListId");

                    b.ToTable("GroceryItems");
                });

            modelBuilder.Entity("BiteAI.Services.Data.Entities.GroceryList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MealPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MealPlanId")
                        .IsUnique();

                    b.ToTable("GroceryLists");
                });

            modelBuilder.Entity("BiteAI.Services.Data.Entities.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Calories")
                        .HasColumnType("integer");

                    b.Property<int>("CarbsInGrams")
                        .HasColumnType("integer");

                    b.Property<int>("FatInGrams")
                        .HasColumnType("integer");

                    b.Property<Guid>("MealDayId")
                        .HasColumnType("uuid");

                    b.Property<int>("MealOrder")
                        .HasColumnType("integer");

                    b.Property<int>("MealType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProteinInGrams")
                        .HasColumnType("integer");

                    b.Property<string>("Recipe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MealDayId");

                    b.HasIndex("MealType");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("BiteAI.Services.Data.Entities.MealDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("MealPlanId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalCalories")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MealPlanId");

                    b.ToTable("MealDays");
                });

            modelBuilder.Entity("BiteAI.Services.Data.Entities.MealPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DailyCalories")
                        .HasColumnType("integer");

                    b.Property<int>("DietType")
                        .HasColumnType("integer");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("DietType");

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("BiteAI.Services.Data.Entities.UserProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int?>("ActivityLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer");

                    b.Property<double?>("HeightInCm")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsProfileComplete")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("OnboardingCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PreferredDietType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("WeightInKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ActivityLevel");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Gender");

                    b.HasIndex("IsProfileComplete");

                    b.HasIndex("PreferredDietType");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("FoodDislikeTypeEntityUserProfile", b =>
                {
                    b.Property<int>("FoodDislikesValue")
                        .HasColumnType("integer");

                    b.Property<string>("UserProfilesId")
                        .HasColumnType("text");

                    b.HasKey("FoodDislikesValue", "UserProfilesId");

                    b.HasIndex("UserProfilesId");

                    b.ToTable("UserProfileFoodDislikes", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AllergyTypeEntityUserProfile", b =>
                {
                    b.HasOne("BiteAI.Services.Data.Entities.Enums.AllergyTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("AllergiesValue")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BiteAI.Services.Data.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BiteAI.Services.Data.Entities.ApplicationUser", b =>
                {
                    b.HasOne("BiteAI.Services.Data.Entities.Enums.ActivityLevelTypeEntity", null)
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("ActivityLevelTypeEntityValue");

                    b.HasOne("BiteAI.Services.Data.Entities.Enums.GenderTypeEntity", null)
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("GenderTypeEntityValue");
                });

            modelBuilder.Entity("BiteAI.Services.Data.Entities.GroceryItem", b =>
                {
                    b.HasOne("BiteAI.Services.Data.Entities.GroceryList", "GroceryList")
                        .WithMany("Items")
                        .HasForeignKey("GroceryListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroceryList");
                });

            modelBuilder.Entity("BiteAI.Services.Data.Entities.GroceryList", b =>
                {
                    b.HasOne("BiteAI.Services.Data.Entities.MealPlan", "MealPlan")
                        .WithOne("GroceryList")
                        .HasForeignKey("BiteAI.Services.Data.Entities.GroceryList", "MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealPlan");
                });

            modelBuilder.Entity("BiteAI.Services.Data.Entities.Meal", b =>
                {
                    b.HasOne("BiteAI.Services.Data.Entities.MealDay", "MealDay")
                        .WithMany("Meals")
                        .HasForeignKey("MealDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BiteAI.Services.Data.Entities.Enums.MealTypeEntity", "MealTypeRelation")
                        .WithMany("Meals")
                        .HasForeignKey("MealType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealDay");

                    b.Navigation("MealTypeRelation");
                });

            modelBuilder.Entity("BiteAI.Services.Data.Entities.MealDay", b =>
                {
                    b.HasOne("BiteAI.Services.Data.Entities.MealPlan", "MealPlan")
                        .WithMany("MealDays")
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealPlan");
                });

            modelBuilder.Entity("BiteAI.Services.Data.Entities.MealPlan", b =>
                {
                    b.HasOne("BiteAI.Services.Data.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("MealPlans")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BiteAI.Services.Data.Entities.Enums.DietTypeEntity", "DietTypeRelation")
                        .WithMany("MealPlans")
                        .HasForeignKey("DietType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("DietTypeRelation");
                });

            modelBuilder.Entity("BiteAI.Services.Data.Entities.UserProfile", b =>
                {
                    b.HasOne("BiteAI.Services.Data.Entities.Enums.ActivityLevelTypeEntity", "ActivityLevelRelation")
                        .WithMany()
                        .HasForeignKey("ActivityLevel")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BiteAI.Services.Data.Entities.Enums.GenderTypeEntity", "GenderRelation")
                        .WithMany()
                        .HasForeignKey("Gender")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BiteAI.Services.Data.Entities.Enums.DietTypeEntity", "PreferredDietTypeRelation")
                        .WithMany()
                        .HasForeignKey("PreferredDietType")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BiteAI.Services.Data.Entities.ApplicationUser", "User")
                        .WithOne("Profile")
                        .HasForeignKey("BiteAI.Services.Data.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityLevelRelation");

                    b.Navigation("GenderRelation");

                    b.Navigation("PreferredDietTypeRelation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodDislikeTypeEntityUserProfile", b =>
                {
                    b.HasOne("BiteAI.Services.Data.Entities.Enums.FoodDislikeTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("FoodDislikesValue")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BiteAI.Services.Data.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BiteAI.Services.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BiteAI.Services.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BiteAI.Services.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BiteAI.Services.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BiteAI.Services.Data.Entities.ApplicationUser", b =>
                {
                    b.Navigation("MealPlans");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("BiteAI.Services.Data.Entities.Enums.ActivityLevelTypeEntity", b =>
                {
                    b.Navigation("ApplicationUsers");
                });

            modelBuilder.Entity("BiteAI.Services.Data.Entities.Enums.DietTypeEntity", b =>
                {
                    b.Navigation("MealPlans");
                });

            modelBuilder.Entity("BiteAI.Services.Data.Entities.Enums.GenderTypeEntity", b =>
                {
                    b.Navigation("ApplicationUsers");
                });

            modelBuilder.Entity("BiteAI.Services.Data.Entities.Enums.MealTypeEntity", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("BiteAI.Services.Data.Entities.GroceryList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BiteAI.Services.Data.Entities.MealDay", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("BiteAI.Services.Data.Entities.MealPlan", b =>
                {
                    b.Navigation("GroceryList");

                    b.Navigation("MealDays");
                });
#pragma warning restore 612, 618
        }
    }
}
